<?php

use Mayden\Pineapple\DB as PineappleDB;

// Map class constants back to global constants
define('DB_OK', PineappleDB::DB_OK);
define('DB_ERROR', PineappleDB::DB_ERROR);
define('DB_ERROR_SYNTAX', PineappleDB::DB_ERROR_SYNTAX);
define('DB_ERROR_CONSTRAINT', PineappleDB::DB_ERROR_CONSTRAINT);
define('DB_ERROR_NOT_FOUND', PineappleDB::DB_ERROR_NOT_FOUND);
define('DB_ERROR_ALREADY_EXISTS', PineappleDB::DB_ERROR_ALREADY_EXISTS);
define('DB_ERROR_UNSUPPORTED', PineappleDB::DB_ERROR_UNSUPPORTED);
define('DB_ERROR_MISMATCH', PineappleDB::DB_ERROR_MISMATCH);
define('DB_ERROR_INVALID', PineappleDB::DB_ERROR_INVALID);
define('DB_ERROR_NOT_CAPABLE', PineappleDB::DB_ERROR_NOT_CAPABLE);
define('DB_ERROR_TRUNCATED', PineappleDB::DB_ERROR_TRUNCATED);
define('DB_ERROR_INVALID_NUMBER', PineappleDB::DB_ERROR_INVALID_NUMBER);
define('DB_ERROR_INVALID_DATE', PineappleDB::DB_ERROR_INVALID_DATE);
define('DB_ERROR_DIVZERO', PineappleDB::DB_ERROR_DIVZERO);
define('DB_ERROR_NODBSELECTED', PineappleDB::DB_ERROR_NODBSELECTED);
define('DB_ERROR_CANNOT_CREATE', PineappleDB::DB_ERROR_CANNOT_CREATE);
define('DB_ERROR_CANNOT_DROP', PineappleDB::DB_ERROR_CANNOT_DROP);
define('DB_ERROR_NOSUCHTABLE', PineappleDB::DB_ERROR_NOSUCHTABLE);
define('DB_ERROR_NOSUCHFIELD', PineappleDB::DB_ERROR_NOSUCHFIELD);
define('DB_ERROR_NEED_MORE_DATA', PineappleDB::DB_ERROR_NEED_MORE_DATA);
define('DB_ERROR_NOT_LOCKED', PineappleDB::DB_ERROR_NOT_LOCKED);
define('DB_ERROR_VALUE_COUNT_ON_ROW', PineappleDB::DB_ERROR_VALUE_COUNT_ON_ROW);
define('DB_ERROR_INVALID_DSN', PineappleDB::DB_ERROR_INVALID_DSN);
define('DB_ERROR_CONNECT_FAILED', PineappleDB::DB_ERROR_CONNECT_FAILED);
define('DB_ERROR_EXTENSION_NOT_FOUND', PineappleDB::DB_ERROR_EXTENSION_NOT_FOUND);
define('DB_ERROR_ACCESS_VIOLATION', PineappleDB::DB_ERROR_ACCESS_VIOLATION);
define('DB_ERROR_NOSUCHDB', PineappleDB::DB_ERROR_NOSUCHDB);
define('DB_ERROR_CONSTRAINT_NOT_NULL', PineappleDB::DB_ERROR_CONSTRAINT_NOT_NULL);
define('DB_PARAM_SCALAR', PineappleDB::DB_PARAM_SCALAR);
define('DB_PARAM_OPAQUE', PineappleDB::DB_PARAM_OPAQUE);
define('DB_PARAM_MISC', PineappleDB::DB_PARAM_MISC);
define('DB_BINMODE_PASSTHRU', PineappleDB::DB_BINMODE_PASSTHRU);
define('DB_BINMODE_RETURN', PineappleDB::DB_BINMODE_RETURN);
define('DB_BINMODE_CONVERT', PineappleDB::DB_BINMODE_CONVERT);
define('DB_FETCHMODE_DEFAULT', PineappleDB::DB_FETCHMODE_DEFAULT);
define('DB_FETCHMODE_ORDERED', PineappleDB::DB_FETCHMODE_ORDERED);
define('DB_FETCHMODE_ASSOC', PineappleDB::DB_FETCHMODE_ASSOC);
define('DB_FETCHMODE_OBJECT', PineappleDB::DB_FETCHMODE_OBJECT);
define('DB_FETCHMODE_FLIPPED', PineappleDB::DB_FETCHMODE_FLIPPED);
define('DB_TABLEINFO_ORDER', PineappleDB::DB_TABLEINFO_ORDER);
define('DB_TABLEINFO_ORDERTABLE', PineappleDB::DB_TABLEINFO_ORDERTABLE);
define('DB_TABLEINFO_FULL', PineappleDB::DB_TABLEINFO_FULL);
define('DB_AUTOQUERY_INSERT', PineappleDB::DB_AUTOQUERY_INSERT);
define('DB_AUTOQUERY_UPDATE', PineappleDB::DB_AUTOQUERY_UPDATE);
define('DB_PORTABILITY_NONE', PineappleDB::DB_PORTABILITY_NONE);
define('DB_PORTABILITY_LOWERCASE', PineappleDB::DB_PORTABILITY_LOWERCASE);
define('DB_PORTABILITY_RTRIM', PineappleDB::DB_PORTABILITY_RTRIM);
define('DB_PORTABILITY_DELETE_COUNT', PineappleDB::DB_PORTABILITY_DELETE_COUNT);
define('DB_PORTABILITY_NUMROWS', PineappleDB::DB_PORTABILITY_NUMROWS);
define('DB_PORTABILITY_ERRORS', PineappleDB::DB_PORTABILITY_ERRORS);
define('DB_PORTABILITY_NULL_TO_EMPTY', PineappleDB::DB_PORTABILITY_NULL_TO_EMPTY);
define('DB_PORTABILITY_ALL', PineappleDB::DB_PORTABILITY_ALL);
define('DB_GETMODE_ORDERED', PineappleDB::DB_FETCHMODE_ORDERED);
define('DB_GETMODE_ASSOC', PineappleDB::DB_FETCHMODE_ASSOC);
define('DB_GETMODE_FLIPPED', PineappleDB::DB_FETCHMODE_FLIPPED);

class DB extends PineappleDB
{
}

class DB_Error extends PineappleDB\Error
{
}

class DB_result extends PineappleDB\Result
{
}

class DB_row extends PineappleDB\Row
{
}
